logger
Yo1k/kaggle_CAFA pull request #6
Opened 2023-08-08 18:42 UTC by JuliaBars

Логгер для записи информации в json: дописываем результаты обучения и параметры модели в уже существующий файл, если он не существует, то создаем новый.

2023-08-08 19:41 UTC, Yo1k requested changes
Нужны небольшие правки.

__К размышлению__, делать не нужно, но такие моменты стоит учитывать: в описании функции сказано, что она добовляет в существующий json-файл информацию. Т.к. нет ограничения на объект `params` (не сказано, что ключи должны быть уникальными), то пользователь может запросто перезаписать какие-то предыдущие записи в файле, а не добавить в него новые. Поэтому на такой случай нужно делать флаг параметр в функции.

2023-08-08 19:41 UTC, Yo1k commented on src/logger.py
> +log_file = DIR_TO_SAVE_LOGS / 'имя файла с логами.json'
Я не понял какую функциональность несут выделенные строки. Объясни пожалуйста.
На мой взгляд достаточно аннотации типа у переменной `log_file`. Если хочется детализировать, то добавь описание параметров в документацию функции (в качестве примера посмотри `model_utils.py`).

2023-08-08 19:41 UTC, Yo1k commented on src/logger.py
> +limit_of_memory = 1073741824  # 1 Гб
Числа с множеством разрядов можно писать `1_073_741_824`,  что повышает читаемость на мой взгляд.
Раз это константа, то _upper_case_ формат. Но логичнее это добавить в виде параметра в функцию с дефолтным значением, пользователь сам решит какого размера делать файлы. Главное в описании функции написать, что файл полность загружается в память.

2023-08-08 19:41 UTC, Yo1k commented on src/logger.py
> +        if log_file.stat().st_size > limit_of_memory:
`log_file.stat().st_size` используется больше одного раза, стоит назначить переменную. Можно сделать 2-мя способами:
1. Через отдельную строку с присвоением переменной.
2. Через оператор `:=`:
```
...
print((file_size := log_file.stat().st_size))
...
```

2023-08-09 07:33 UTC, JuliaBars commented on src/logger.py
> +limit_of_memory = 1073741824  # 1 Гб
DONE

2023-08-09 07:35 UTC, JuliaBars commented on src/logger.py
> +log_file = DIR_TO_SAVE_LOGS / 'имя файла с логами.json'
Это осталось с тестирования кода, убрала

2023-08-09 07:46 UTC, Yo1k approved these changes

2023-08-09 07:47 UTC, merged